config/routes.rb
Rails.application.routes.draw do
  #ホーム画面
  root to: 'products#index'

  #生産者情報関連
  devise_for :producers, controllers: {
    sessions:      'producers/sessions',
    passwords:     'producers/passwords',
    registrations: 'producers/registrations'
  }
  resources :producers, only: %i[show]

  #消費者情報関連
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, only: %i[show]

  #ブログ機能
  resources :blogs, only: %i(index new create show edit update destroy)

  #管理者
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #商品関連
  resources :products
  resources :products do
    #コメント
    resources :comments
    #購入処理
    resources :purchases, only: %i[index] do
      collection do
        get 'index', to: 'purchases#index'
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end

  #商品のお気に入り
  resources :favorite_persons, only: %i[create destroy index]

  #生産者のお気に入り
  resources :favorites, only: %i[create destroy index]

  #メッセージ一覧画面
  resources :message_tops, only: %i[index]

  #メッセージルーム
  resources :rooms, only: %i[show create] do
    resources :messages, only: %i[create]
  end

  #カード情報関連
  resources :cards, only: %i[new show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :producer, optional: true
  belongs_to :user, optional: true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/favorite_person.rb
class FavoritePerson < ApplicationRecord
  belongs_to :user
  belongs_to :producer
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :products, through: :labelings
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :product
  belongs_to :label
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

app/models/producer.rb
class Producer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :producer_name, presence: true
  validates :email, presence: true
  validates :producer_postal_code, presence: true
  validates :producer_prefecture_code, presence: true
  validates :producer_address_city, presence: true
  validates :producer_address_street, presence: true

  has_many :products
  has_many :rooms
  has_many :favorite_persons, dependent: :destroy
  has_many :favorite_person_users, through: :favorite_persons, source: :user
  has_one_attached :producer_avatar
  has_many :blogs, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many_attached :sub_images
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  has_many :comments, dependent: :destroy
  belongs_to :producer

  validates :title, presence: true ,length: { maximum: 25 }
  validates :price, presence: true
  validates :quantity, presence: true
  validate :image_presence
  validates :content, presence:true ,length: { maximum: 300 }
  validate :date_not_before_today
  validates :harvest_date, presence:true
  validates :farm_name, presence:true
  validates :farm_street_address, presence:true

  def image_presence
    if image.attached?
    else
      errors.add(:image, 'ファイルを添付してください')
    end
  end

  def date_not_before_today
    errors.add(:harvest_date, "は本日以前のものを選択してください") if harvest_date.nil? || harvest_date > Date.today
  end

  scope :title_search, -> (title) {where("title LIKE ?", "%#{title}%")}
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :producer

  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   include JpPrefecture
   jp_prefecture :prefecture_code, method_name: :pref


   def prefecture_name
     JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
   end

   def prefecture_name=(prefecture_name)
     self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
   end

   validates :name, presence: true
   validates :email, presence: true
   validates :postal_code, presence: true
   validates :prefecture_code, presence: true
   validates :address_city, presence: true
   validates :address_street, presence: true

   has_one :credit_card, dependent: :destroy
   has_many :rooms
   has_many :favorites, dependent: :destroy
   has_many :favorite_persons, dependent: :destroy
   has_one_attached :avatar
   has_many :blogs, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_product, only: %i[create edit update]

  def create
    @comment = @product.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to product_path(@product), notice: '投稿できませんでした...' }
      end
    end
  end

  def edit
    @comment = @product.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = @product.comments.find(params[:id])
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:notice] = 'コメントが編集されました'
          format.js { render :index }
        else
          flash.now[:notice] = 'コメントの編集に失敗しました'
          format.js { render :edit_error }
        end
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:product_id, :content)
  end

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_edit.html.erb
<%= form_with(model: [product, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content %><br/>
    <%= form.text_area :content, id: "comment_content_#{product.id}" ,class: "form-control" ,placeholder: "ここに編集するコメントを入力します"%><br>
  </div>
  <div class="actions">
    <%= form.submit class: "form-control btn btn-info" , id: "edit_comment"%>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [product, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content %><br/>
    <%= form.text_area :content ,class: "form-control"%>
  </div>
  <div class="actions mt-4">
    <%= form.submit class: "form-control btn btn-info" , id: "create_comment"%>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li class="list-unstyled">
        <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
        <%= comment.content %>
        <hr>
        <%= link_to "コメント編集", edit_product_comment_path(product, comment), remote: true , class: "text-info float-right"%>
        <br>
        <%= link_to "コメント削除", product_comment_path(comment.product_id, comment.id), method: :delete, remote: true, class: "text-info float-right"%>
      </li>
    <% end %>
    <br>
  <% end %>
</ul>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', product: @product, comment: @comment %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.product.comments, product: @comment.product }) %>")
$("textarea").val('')