config/routes.rb
Rails.application.routes.draw do
  #ホーム画面
  root to: 'products#index'

  #生産者情報関連
  devise_for :producers, controllers: {
    sessions:      'producers/sessions',
    passwords:     'producers/passwords',
    registrations: 'producers/registrations'
  }
  resources :producers, only: %i[show]

  #消費者情報関連
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, only: %i[show]

  #ブログ機能
  resources :blogs, only: %i(index new create show edit update destroy)

  #管理者
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #商品関連
  resources :products
  resources :products do
    #コメント
    resources :comments
    #購入処理
    resources :purchases, only: %i[index] do
      collection do
        get 'index', to: 'purchases#index'
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end

  #商品のお気に入り
  resources :favorite_persons, only: %i[create destroy index]

  #生産者のお気に入り
  resources :favorites, only: %i[create destroy index]

  #メッセージ一覧画面
  resources :message_tops, only: %i[index]

  #メッセージルーム
  resources :rooms, only: %i[show create] do
    resources :messages, only: %i[create]
  end

  #カード情報関連
  resources :cards, only: %i[new show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :producer, optional: true
  belongs_to :user, optional: true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/favorite_person.rb
class FavoritePerson < ApplicationRecord
  belongs_to :user
  belongs_to :producer
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :products, through: :labelings
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :product
  belongs_to :label
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

app/models/producer.rb
class Producer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :producer_name, presence: true
  validates :email, presence: true
  validates :producer_postal_code, presence: true
  validates :producer_prefecture_code, presence: true
  validates :producer_address_city, presence: true
  validates :producer_address_street, presence: true

  has_many :products
  has_many :rooms
  has_many :favorite_persons, dependent: :destroy
  has_many :favorite_person_users, through: :favorite_persons, source: :user
  has_one_attached :producer_avatar
  has_many :blogs, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many_attached :sub_images
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  has_many :comments, dependent: :destroy
  belongs_to :producer

  validates :title, presence: true ,length: { maximum: 25 }
  validates :price, presence: true
  validates :quantity, presence: true
  validate :image_presence
  validates :content, presence:true ,length: { maximum: 300 }
  validate :date_not_before_today
  validates :harvest_date, presence:true
  validates :farm_name, presence:true
  validates :farm_street_address, presence:true

  def image_presence
    if image.attached?
    else
      errors.add(:image, 'ファイルを添付してください')
    end
  end

  def date_not_before_today
    errors.add(:harvest_date, "は本日以前のものを選択してください") if harvest_date.nil? || harvest_date > Date.today
  end

  scope :title_search, -> (title) {where("title LIKE ?", "%#{title}%")}
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :producer

  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   include JpPrefecture
   jp_prefecture :prefecture_code, method_name: :pref


   def prefecture_name
     JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
   end

   def prefecture_name=(prefecture_name)
     self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
   end

   validates :name, presence: true
   validates :email, presence: true
   validates :postal_code, presence: true
   validates :prefecture_code, presence: true
   validates :address_city, presence: true
   validates :address_street, presence: true

   has_one :credit_card, dependent: :destroy
   has_many :rooms
   has_many :favorites, dependent: :destroy
   has_many :favorite_persons, dependent: :destroy
   has_one_attached :avatar
   has_many :blogs, dependent: :destroy
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new", alert: "クレジットカードを登録できませんでした。"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト',
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new", alert: "クレジットカードを情報がありません。"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new", alert: "クレジットカードを削除できませんでした。"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/new.html.erb
<div class="container" style="padding-top:2.5rem; padding-bottom:2.5rem;">
  <div class="mx-auto p-4  border border-primary rounded" style="border:solid 1px; max-width:40rem;">
    <h3 class="home_title text-primary">クレジットカード情報入力</h3>
    <%= form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do %>
      <div class="form-group" style="padding-top:1rem;">
        <label>カード番号</label>
        <span class="required alert-danger rounded">※必須</span>
        <br/>
        <%= text_field_tag "number", "", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number" , :size=>"5",:class => "form-control" %>
      </div>
      <label>有効期限</label>
      <span class="required alert-danger rounded">※必須</span><br/>
      <div class="form-row">
        <div class="form-group col-md-3">
          <select class="card-valid form-control" id="exp_month" name="exp_month" type="text">
            <option>--</option>
            <option value="1">01</option>
            <option value="2">02</option>
            <option value="3">03</option>
            <option value="4">04</option>
            <option value="5">05</option>
            <option value="6">06</option>
            <option value="7">07</option>
            <option value="8">08</option>
            <option value="9">09</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
          </select>
          </div>
          <span>月/</span>
          <div class="form-group col-md-3">
          <select class="card-valid form-control" id="exp_year" name="exp_year" type="text">
            <option>--</option>
            <option value="2020">20</option>
            <option value="2021">21</option>
            <option value="2022">22</option>
            <option value="2023">23</option>
            <option value="2024">24</option>
            <option value="2025">25</option>
            <option value="2026">26</option>
            <option value="2027">27</option>
            <option value="2028">28</option>
            <option value="2029">29</option>
            <option value="2030">30</option>
          </select>
        </div>
        <span>年</span>
      </div>
      <div class="form-group">
        <label class="">セキュリティコード</label>
        <span class="required alert-danger rounded">※必須</span>
        <br/>
        <%= text_field_tag "cvc", "", class: "form-control", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc" %>
      </div>
      <div class="form-group">
        <div id="card_token"></div>
        <%= submit_tag "カード登録を行う", id: "token_submit", class: 'btn btn-info ' %>
      </div>
    <% end %>
  </div>
</div>

app/views/cards/show.html.erb
<div class="container" style="padding-top:2.5rem; padding-bottom:2.5rem;">
  <div class="mx-auto p-4  border border-primary rounded" style="border:solid 1px; max-width:40rem;">
    <h4 class="home_title text-primary text-center">登録クレジットカード</h4>
    <div style="padding-top:1rem; padding-bottom:1rem;">
      <label class="required text-primary">カード番号</label><br/>
      <%= "**** **** **** " + @default_card_information.last4%>
    </div>
    <div style="padding-top:1rem; padding-bottom:1rem;">
      <label class="required text-primary">有効期限</label><br/>
      <% exp_month = @default_card_information.exp_month.to_s %>
      <% exp_year = @default_card_information.exp_year.to_s.slice(2,3) %>
      <%= exp_month + " / " + exp_year %>
    </div>
    <%= form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do %>
      <input name="card_id" type="hidden">
      <button class='float-right btn btn-info'>削除する</button><br/>
    <% end %>
  </div>
</div>