config/routes.rb
Rails.application.routes.draw do
  #ホーム画面
  root to: 'products#index'

  #生産者情報関連
  devise_for :producers, controllers: {
    sessions:      'producers/sessions',
    passwords:     'producers/passwords',
    registrations: 'producers/registrations'
  }
  resources :producers, only: %i[show]

  #消費者情報関連
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, only: %i[show]

  #ブログ機能
  resources :blogs, only: %i(index new create show edit update destroy)

  #管理者
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #商品関連
  resources :products
  resources :products do
    #コメント
    resources :comments
    #購入処理
    resources :purchases, only: %i[index] do
      collection do
        get 'index', to: 'purchases#index'
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end

  #商品のお気に入り
  resources :favorite_persons, only: %i[create destroy index]

  #生産者のお気に入り
  resources :favorites, only: %i[create destroy index]

  #メッセージ一覧画面
  resources :message_tops, only: %i[index]

  #メッセージルーム
  resources :rooms, only: %i[show create] do
    resources :messages, only: %i[create]
  end

  #カード情報関連
  resources :cards, only: %i[new show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/producer.rb
class Producer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :producer_name, presence: true
  validates :email, presence: true
  validates :producer_postal_code, presence: true
  validates :producer_prefecture_code, presence: true
  validates :producer_address_city, presence: true
  validates :producer_address_street, presence: true

  has_many :products
  has_many :rooms
  has_many :favorite_persons, dependent: :destroy
  has_many :favorite_person_users, through: :favorite_persons, source: :user
  has_one_attached :producer_avatar
  has_many :blogs, dependent: :destroy
end

app/controllers/producers/confirmations_controller.rb
# frozen_string_literal: true

class Producers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/producers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Producers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/producers/passwords_controller.rb
# frozen_string_literal: true

class Producers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/producers/registrations_controller.rb
# frozen_string_literal: true

class Producers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/producers/sessions_controller.rb
# frozen_string_literal: true

class Producers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/producers/unlocks_controller.rb
# frozen_string_literal: true

class Producers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  def show
    @producer = Producer.find(params[:id])

    if user_signed_in?
      @favorite_person = current_user.favorite_persons.find_by(producer_id: @producer.id)
    end
  end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/show.html.erb
<br>
<div class="mx-auto p-4 border border-primary rounded" style="border:solid 1px #343a40; max-width:500px;">
  <h3 class="home_title text-center">生産者プロフィール画面</h3><br/>
  <% if @producer.producer_avatar.attached? %>
    <%= image_tag @producer.producer_avatar.variant(combine_options:{gravity: :center,
                                                        border:'2',
                                                        resize:"160x160^",
                                                        crop:"220x220+0+0"}).processed,
                                                        class: "img border-primary"%><br/>
  <% end %>
  <br>
  <h5>生産者名</h5>
  <p class="form-control alert alert-warning rounded"><%= @producer.producer_name %></p>
  <h5>生産者メールアドレス</h5>
  <p class="form-control alert alert-warning rounded"><%= @producer.email %></p><br/>
  <div class="row">
    <div class="ml-2 mr-2">
      <% if user_signed_in? %>
        <% if @favorite_person.present? %>
          <%= link_to 'お気に入り解除する', favorite_person_path(id: @favorite_person.id), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to '生産者をお気に入りにする', favorite_persons_path(producer_id: @producer.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
  <div class="text-primary" style="margin-bottom:30px;">
    <h5 class="home_title text-center">商品一覧</h5>
  </div>
  <div class="col">
    <div class="row">
      <% @producer.products.each do |product|%>
        <tr>
          <div class="card ml-2 mb-2 mr-2 rounded border-primary" style="width: 13rem;">
            <% if product.image.attached? %>
              <td><%= image_tag product.image.variant(combine_options:{gravity: :center,border:'2', resize:"180x180^",crop:"220x220+0+0"}).processed ,class: "rounded"%></td>
            <% end %>
            <div class="card-body">
              <div class="example">
                <div class="box">
                  <%= link_to producer_path(product.producer.id) do%>
                    <%= product.producer.producer_name %>
                  <% end %>
                </div>
                <% if product.producer.producer_avatar.attached? %>
                  <% if product.quantity == 0%>
                  <p>soldout</p>
                  <% end %>
                <% end %>
              </div>
              <td>
                <%= link_to product_path(product.id) do%>
                  <%= product.title.truncate(20) %>
                <% end %>
              </td><br/>
              <td><h5 class="text-primary">¥ <%= product.price %></h5></td>
              <td><%= product.content.truncate(23) %></td><br/>
              <% if current_user.try(:admin?) || producer_signed_in? %>
                <% if current_user.try(:admin?) || current_producer.id == product.producer.id%>
                  <td><%= link_to "編集", edit_product_path(product.id) , class: "btn btn-primary mb-1" %></td>
                <% end %>
              <% end %>
              <% if current_user.try(:admin?) %>
                <td><%= link_to '削除', product_path(product.id), method: :delete , data: { confirm: '本当に削除していいですか？' } , class: "btn btn-primary mb-1" %></td><br/>
              <% end %>
              <td class="product_label">
                <% product.labels.each do |label| %>
                  <label class='btn-sticky'><%= label.name %></label>
                <% end %>
              </td>
            </div>
          </div>
        </tr>
      <% end %>
    </div>
  </div>
</div>