config/routes.rb
Rails.application.routes.draw do
  #ホーム画面
  root to: 'products#index'

  #生産者情報関連
  devise_for :producers, controllers: {
    sessions:      'producers/sessions',
    passwords:     'producers/passwords',
    registrations: 'producers/registrations'
  }
  resources :producers, only: %i[show]

  #消費者情報関連
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resources :users, only: %i[show]

  #ブログ機能
  resources :blogs, only: %i(index new create show edit update destroy)

  #管理者
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  #商品関連
  resources :products
  resources :products do
    #コメント
    resources :comments
    #購入処理
    resources :purchases, only: %i[index] do
      collection do
        get 'index', to: 'purchases#index'
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end

  #商品のお気に入り
  resources :favorite_persons, only: %i[create destroy index]

  #生産者のお気に入り
  resources :favorites, only: %i[create destroy index]

  #メッセージ一覧画面
  resources :message_tops, only: %i[index]

  #メッセージルーム
  resources :rooms, only: %i[show create] do
    resources :messages, only: %i[create]
  end

  #カード情報関連
  resources :cards, only: %i[new show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :producer, optional: true
  belongs_to :user, optional: true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/favorite_person.rb
class FavoritePerson < ApplicationRecord
  belongs_to :user
  belongs_to :producer
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :products, through: :labelings
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :product
  belongs_to :label
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

app/models/producer.rb
class Producer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :producer_name, presence: true
  validates :email, presence: true
  validates :producer_postal_code, presence: true
  validates :producer_prefecture_code, presence: true
  validates :producer_address_city, presence: true
  validates :producer_address_street, presence: true

  has_many :products
  has_many :rooms
  has_many :favorite_persons, dependent: :destroy
  has_many :favorite_person_users, through: :favorite_persons, source: :user
  has_one_attached :producer_avatar
  has_many :blogs, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many_attached :sub_images
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  has_many :comments, dependent: :destroy
  belongs_to :producer

  validates :title, presence: true ,length: { maximum: 25 }
  validates :price, presence: true
  validates :quantity, presence: true
  validate :image_presence
  validates :content, presence:true ,length: { maximum: 300 }
  validate :date_not_before_today
  validates :harvest_date, presence:true
  validates :farm_name, presence:true
  validates :farm_street_address, presence:true

  def image_presence
    if image.attached?
    else
      errors.add(:image, 'ファイルを添付してください')
    end
  end

  def date_not_before_today
    errors.add(:harvest_date, "は本日以前のものを選択してください") if harvest_date.nil? || harvest_date > Date.today
  end

  scope :title_search, -> (title) {where("title LIKE ?", "%#{title}%")}
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :producer

  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   include JpPrefecture
   jp_prefecture :prefecture_code, method_name: :pref


   def prefecture_name
     JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
   end

   def prefecture_name=(prefecture_name)
     self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
   end

   validates :name, presence: true
   validates :email, presence: true
   validates :postal_code, presence: true
   validates :prefecture_code, presence: true
   validates :address_city, presence: true
   validates :address_street, presence: true

   has_one :credit_card, dependent: :destroy
   has_many :rooms
   has_many :favorites, dependent: :destroy
   has_many :favorite_persons, dependent: :destroy
   has_one_attached :avatar
   has_many :blogs, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy pay]
  before_action :authenticate_user!, only: %i[pay]

  def index
    @products = Product.all.order(id: "DESC").page(params[:page]).per(16)

    if params[:search].present?
      @products = Product.title_search(params[:title]).page(params[:page]).per(16)
    end

    if params[:label_id].present?
      @products = @products.joins(:labels).where(labels: { id: params[:label_id] })
    end
  end

  def new
    @product = current_producer.products.build
  end

  def create
    @product = current_producer.products.build(product_params)
    if @product.save
      redirect_to products_path, notice: "出品完了しました！"
    else
      render :new
    end
  end

  def show
    if user_signed_in?
      @favorite = current_user.favorites.find_by(product_id: @product.id)
    end
    @comments = @product.comments
    @comment = @product.comments.build
  end

  def edit
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path, notice: "商品情報を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice:"商品を削除しました！"
  end

  private

  def product_params
    params.require(:product).permit(
      :title,
      :price,
      :quantity,
      :image,
      :content,
      :category,
      :harvest_date,
      :farm_name,
      :farm_street_address,
      sub_images: [],
      label_ids: [])
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true)do |form| %>
  <% if @product.errors.any? %>
    <div class="mx-auto p-2 border border-warning rounded" style="border:solid 1px; max-width:500px; margin-bottom:40px;">
      <div id="error_explanation" class="text-danger">
        <h3 class="alert alert-warning rounded"><%= @product.errors.count %>件のエラーがあります。</h3>
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li class="list-unstyled"><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title ,class: "text-primary"%><br />
    <%= form.text_field :title, autoformocus: true , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price ,class: "text-primary"%><br />
    <%= form.text_field :price, autoformocus: true , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :quantity ,class: "text-primary"%><br />
    <%= form.text_field :quantity, autoformocus: true , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image ,class: "text-primary"%><br/>
    <%= form.label :image, class: "btn btn-info" do %>
      <i class="far fa-image"> メイン画像ファイルを選択</i>
    <% end %>
    <%= form.file_field :image, class: "image_form", style: "display: none;"%>
    <%= form.label :sub_images, class: "btn btn-warning" do %>
      <i class="far fa-image"> サブ画像ファイルを選択(3枚まで)</i>
    <% end %>
    <%= form.file_field :sub_images, class: "image_form", multiple: true, style: "display: none;"%>
  </div>


  <div class="form-group">
    <%= form.label :content ,class: "text-primary"%><br />
    <%= form.text_area :content, size: "2x10", autoformocus: true , class: "form-control" ,placeholder: "※300文字まで"%>
  </div>

  <div class="form-group">
    <%= form.label :harvest_date ,class: "text-primary"%><br />
    <%= form.date_field :harvest_date %>
  </div>

  <div class="form-group">
    <%= form.label :farm_name ,class: "text-primary" %><br />
    <%= form.text_field :farm_name, autoformocus: true , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :farm_street_address ,class: "text-primary" %><br />
    <%= form.text_field :farm_street_address, autoformocus: true , class: "form-control" %>
  </div>

  <div class="task_label">
    <%= form.label :label, "生産品にラベルをつけてみよう↓↓" ,class: "text-primary"%><br/>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>

  <div class="actions mt-4">
    <%= form.submit name="出品する"  , class: "form-control btn btn-info"%>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="mx-auto p-4 border border-primary rounded" style="border:solid 1px; max-width:700px;">
  <h2 class="text-center home_title text-primary" style="margin-bottom:40px;">商品を編集する</h2>
  <%= render 'form' %>
</div>

app/views/products/index.html.erb
<div class="bg-light">
  <div class="carousel">
    <% @products.shuffle.first(6).each do |product|%>
      <div class="card">
        <div class="card-header">
          <% if product.image.attached? %>
            <td><%= image_tag product.image.variant(combine_options:{gravity: :center,border:'2', resize:"180x180^",crop:"220x220+0+0"}).processed ,class: "rounded"%></td>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-content">
            <div class="example">
              <div class="box">
                <%= link_to producer_path(product.producer.id) do%>
                  <%= product.producer.producer_name %>
                <% end %>
              </div>
              <% if product.producer.producer_avatar.attached? %>
                <% if product.quantity == 0%>
                  <p>soldout</p>
                <% end %>
              <% end %>
            </div>
            <div class="card-title">
              <%= link_to product_path(product.id) do%>
                <%= product.title.truncate(20) %>
              <% end %>
            </div>
            <div class="card-text">
              <td><h5 class="text-primary">¥ <%= product.price %></h5></td>
              <td><%= product.content.truncate(23) %></td><br>
              <td class="product_label">
                <% product.labels.each do |label| %>
                  <label class='btn-sticky'><%= label.name %></label>
                <% end %>
              </td>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="container bg-white">
    <div class="text-center text-primary" style="margin-bottom:30px;">
      <% if current_user.try(:admin?) %>
        <h2 class="home_title text-primary">商品一覧(管理者用)</h2>
      <% else %>
        <h2 class="home_title text-primary">商品一覧</h2>
      <% end %>
    </div>

    <div class="row">
      <div class="form-group float-left">
        <%= form_with(url:products_path, local: true, method: :get) do |form| %>
          <%= form.label :title_search, class: "text-primary" do %>
            <i class="fas fa-leaf"> タイトル検索</i>
          <% end %><br/>
          <%= form.text_field :title ,class:"form-control"%><br/>
          <%= form.label :label_id_search, class: "text-primary" do %>
            <i class="fas fa-tags"> ラベル検索</i>
          <% end %><br/>
          <%= form.select("label_id", Label.all.pluck(:name, :id), { include_blank:"選択する",include_hidden: false },  {  class: "form-control" }) %><br/>
          <%= form.hidden_field :search, value:"true" %>
          <%= form.submit name="検索する" , class: "form-control btn btn-info"%>
        <% end %>
      </div>
      <div class="col">
        <div class="row">
          <% @products.each do |product|%>
            <tr>
              <div class="card ml-2 mb-2 mr-2 rounded border-primary" style="width: 13rem;">
                <% if product.image.attached? %>
                  <td><%= image_tag product.image.variant(combine_options:{gravity: :center,border:'2', resize:"180x180^",crop:"220x220+0+0"}).processed ,class: "rounded"%></td>
                <% end %>
                <div class="card-body">
                  <div class="example">
                    <div class="box">
                      <%= link_to producer_path(product.producer.id) do%>
                        <%= product.producer.producer_name %>
                      <% end %>
                    </div>
                    <% if product.producer.producer_avatar.attached? %>
                      <% if product.quantity == 0%>
                      <p>soldout</p>
                          <%= image_tag product.producer.producer_avatar.variant(combine_options:{gravity: :center,
                                                                          border:'2',
                                                                          resize:"50x95^",
                                                                          crop:"100x100+0+0"}).processed,
                                                                          class: "img border-primary"
                                                                          %>
                      <% else %>
                      <%= image_tag product.producer.producer_avatar.variant(combine_options:{gravity: :center,
                                                                      border:'2',
                                                                      resize:"50x95^",
                                                                      crop:"100x100+0+0"}).processed,
                                                                      class: "img border-primary"
                                                                      %>
                      <% end %>
                    <% end %>
                  </div>
                  <td>
                    <%= link_to product_path(product.id) do%>
                      <%= product.title.truncate(20) %>
                    <% end %>
                  </td><br/>
                  <td><h5 class="text-primary">¥ <%= product.price %></h5></td>
                  <td><%= product.content.truncate(23) %></td><br/>
                  <% if current_user.try(:admin?) || producer_signed_in? %>
                    <% if current_user.try(:admin?) || current_producer.id == product.producer.id%>
                      <td><%= link_to "編集", edit_product_path(product.id) , class: "btn btn-primary mb-1" %></td>
                    <% end %>
                  <% end %>
                  <% if current_user.try(:admin?) %>
                    <td><%= link_to '削除', product_path(product.id), method: :delete , data: { confirm: '本当に削除していいですか？' } , class: "btn btn-primary mb-1" %></td><br/>
                  <% end %>
                  <td class="product_label">
                    <% product.labels.each do |label| %>
                      <label class='btn-sticky'><%= label.name %></label>
                    <% end %>
                  </td>
                </div>
              </div>
            </tr>
          <% end %>
        </div>
      </div>
    </div>
    <div class="my-4 mx-auto" style="width: 200px;">
      <%= paginate @products %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="mx-auto p-4 border border-primary rounded" style="border:solid 1px; max-width:700px;">
  <h2 class="text-center home_title text-primary" style="margin-bottom:40px;">商品を出品する</h2>
  <%= render 'form' %>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="mx-auto p-4 my-4 border border-primary rounded" style="border:solid 1px; max-width:1000px;">
    <h3 class="home_title text-primary text-center">商品詳細画面</h3>
    <div class="alert alert-light" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
    <div class="product-text rounded" style="ax-width:1000px;">
      <div class="row ml-2 mb-2 mr-2">
        <div class="row mr-2">
        <% if @product.image.attached? %>
          <p>
            <%= image_tag @product.image.variant(combine_options:{gravity: :center,border:'2', resize:"180x180^",crop:"220x220+0+0"}).processed ,class: "rounded"%>
          </p>
        <% end %>
        </div>
        <% if @product.sub_images.attached? %>
          <p>
            <% @product.sub_images.first(3).each do |sub_image| %>
              <%= image_tag sub_image.variant(combine_options:{gravity: :center,border:'2', resize:"180x180^",crop:"220x220+0+0"}).processed ,class: "rounded"%>
            <% end %>
          </p>
        <% end %>
      </div>
      <p class="form-control text-primary font-weight-bold border border-primary rounded"><%= @product.title %></p>
      <p>
        <% @product.labels.each do |label| %>
          <label class='btn-sticky'><%= label.name %></label>
        <% end %>
      </p>
      <p class="alert alert-warning rounded">価格: <%= @product.price %></p>
      <p class="alert alert-warning rounded">在庫数: <%= @product.quantity %></p>
      <p class="alert alert-warning rounded">詳細:<br/> <%= @product.content %></p>
      <p class="alert alert-warning rounded">収穫日: <%= @product.harvest_date.strftime("%Y年%m月%d日")%></p>
      <p class="alert alert-warning rounded">農園名: <%= @product.farm_name %></p>
      <p class="alert alert-warning rounded">運営者先住所: <%= @product.farm_street_address %></p>
    </div>
    <br>
    <% if user_signed_in? %>
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りリストへ', favorites_path(product_id: @product.id), method: :post, class: 'btn btn-primary' %>
      <% end %><br/>
    <br>
      <% if @product.quantity > 0 %>
        <%= link_to '購入する', product_purchases_path(product_id: @product.id), class: "btn btn-info mb-1" %>
      <% elsif @product.quantity == 0 %>
        <strong>申し訳ございません。当商品は売り切れです🙇‍♂️</strong>
      <% end %>
    <% elsif producer_signed_in?%>
      <strong><お願い></strong>
      <p>他出品者の商品ご購入を希望する場合は、<br>
        お手数ですが生産者ではなく、ユーザー新規登録、ログインからご購入してください🙇‍♂️</p>
    <% else %>
      <p>※商品ご購入を希望の場合はユーザー新規登録、ログインをしてください🙇‍♂️</p>
      <%= link_to "ユーザー新規登録", new_user_registration_path, class: 'nav-link'%>
    <% end %>
  </div>
  <br>
  <div class="card mx-auto border border-primary rounded" style="max-width:1000px;">
    <div class="card-body p-4">
      <div class="text-center my-3">
        <strong>コメント一覧</strong>
        <p id="notice"><%= notice %></p>
      </div>
      <div id="comments_area">
        <%= render partial: 'comments/index', locals: { comments: @comments, product: @product } %>
      </div>
      <%= render partial: 'comments/form', locals: { comment: @comment, product: @product } , class: "text-info float-right"%>
      <%= link_to '一覧画面に戻る', products_path , class: "text-info float-right"%>
    </div>
  </div>
</div>